/* 
 * File:   EulerP2.cpp
 * Author: Konstantin Kazantsev
 * CSCI 372.2 C++
 *
 * Created on January 30, 2015, 12:05 PM
 * 
 * Euler Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

#include <cstdlib>
#include <iostream>

using namespace std;

int main(int argc, char** argv) {
    long n1 = 1;
    long n2 = 2;
    long n3 = 0;

    cout << n1 << endl;
    cout << n2 << endl;
    while ((n2+n1) < 4400000) {
        long n3 = n1 + n2;
        cout<<n3<<endl;
        n1 = n2;
        n2 = n3;  
    }

    return 0;
}

